language: node_js
node_js:
  - "8"
  - "10"

sudo: false
cache:
  directories:
    - node_modules

script:
  - npm run coverage

after_success:
  - npm i codecov
  - nyc report --reporter=lcov > codecov.info && codecov
