#!/usr/bin/env node
'use strict';

const path = require('path');
const run = require('../tools/run');

const ROOT_DIR = path.resolve(__dirname, '../');
const isWin = process.platform === 'win32';

const cmd = 'npx pm2 startup';

console.log('Configuring pm2 to setup startup on system boot.');
console.log(`
This will make it so that the reminder-app will
start automatically by pm2 on your os startup.
Note: This may require admin (sudo / elavated terminal) access
and may fail if not the case.
`);

const opts = {
  cwd: ROOT_DIR
};

process.env.NODE_ENV = 'production';
process.env.PORT = process.env.PORT || 7000;

async function savePm2List() {
  await run('npx pm2 start app --name reminder-app', opts);
  await run('npx pm2 save', opts);
}

function init_startup_win() {
  const winstart = require('start-on-windows-boot');
  return new Promise(resolve => {
    const file = path.join(__dirname, 'reminder-app.exe');
    winstart.enableAutoStart('reminder-app', file, async () => {
      await savePm2List();
      resolve();
    });
  });
}

async function init_startup_unix() {
  let output;
  try {
    await run(cmd, {
      ...opts,
      silent: true,
      capture: true
    });
  } catch(e) {
    // ignore the error, since pm2 exits with code of 1,
    // eventhough everything goes successful.
    output = e.output;
  }

  let startupCmd = '';
  output = output || '';
  output = output.split('\n');
  output.forEach(text => {
    if (!text.startsWith('[pm2]') && text !== '') {
      startupCmd = text;
    }
  });

  console.log('Running startup config command:');
  await run(startupCmd, { shell: true });
  await savePm2List();
}

const init_startup = isWin ? init_startup_win : init_startup_unix;
init_startup()
  .then(() => {
    console.log();
    console.log('Reminder App will now start on os bootup!');
  })
  .catch(e => {
    console.error('Failed to setup reminder-app to startup on restart!');
    console.error('Its likely that you need admin/sudo access to set this up sucessfully!');
    console.error();
    console.error('Traceback: ');
    console.error(e);
  });
