#!/usr/bin/env node
'use strict';

const path = require('path');
const pm2 = require('./lib/pm2');
const run = require('../tools/run');

const ROOT_DIR = path.resolve(__dirname, '../');
async function restart() {
  await pm2.runPm2UpdateIfNeeded();
  await run('npx pm2 reload reminder-app --update-env', {
    cwd: ROOT_DIR
  });
}

restart();
