#!/usr/bin/env node
'use strict';

const path = require('path');
const pm2 = require('./pm2');
const run = require('../tools/run');

async function start() {
  await pm2.runPm2UpdateIfNeeded();
  await run('npx pm2 start app --name reminder-app', {
    silent: true,
    cwd: path.resolve(__dirname, '..')
  });
}

start();
