#!/usr/bin/env node
'use strict';

const path = require('path');
const fs = require('fs');
const url = require('url');
const fsExtra = require('fs-extra');
const glob = require('glob');
const tsNode = require('ts-node');
const ArgParser = require('../app/argparser');
const env = require('../app/env');
const run = require('./run');

// to make test runnable from anywhere
const TEST_DIR = path.resolve(__dirname, '../test/app/');
process.chdir(TEST_DIR);
tsNode.register();

env.setEnv('tests', true);
env.setEnv('mode', 'tests');
env.setEnv('development', true);

const args = new ArgParser(`
Run app tests:

Usage:
./tools/app-tests <filename>
./tools/app-tests # to run all the tests
`);

args.parse();
let testFiles = args.nargs;
if (!testFiles) {
  testFiles = glob.sync('**/*.js');
}

const DB_PATH = path.join(__dirname, `../var/reminder-app-${env.mode}`);
fsExtra.removeSync(DB_PATH);

global.assert = require('assert');
global.fetch = require('node-fetch');

process.env.PORT = '8827';
process.env.NODE_ENV = 'production';
const request = require('../static/js/request');
class ExtendedRequest {
  constructor() {
    this.request = request;
    this.baseURL = `http://localhost:${process.env.PORT}`;
  }

  getURL(passedUrl) {
    const { baseURL } = this;
    return url.resolve(baseURL, passedUrl);
  }

  post(url, ...args) {
    return request.post(this.getURL(url), ...args);
  }

  get(url, ...args) {
    return request.get(this.getURL(url), ...args);
  }
}

global.request = new ExtendedRequest();

async function assertPromiseThrows(func, exception) {
  let error;
  await func().catch(err => { error = err; });
  global.assert.throws(() => {
    if (error)
      throw error;
  }, exception);
}

global.assertPromiseThrows = assertPromiseThrows;

function startServer() {
  process.argv.push('--tests');
  const app = require('../app');
  global.app = app;

  const serverReady = new Promise((resolve) => {
    app.on('server-ready', (server) => {
      resolve(server);
    });
  });

  return serverReady;
}

const ROOT_DIR = path.resolve(__dirname, '../');
const WEBPACK_BUNDLE_FILE = path.resolve(__dirname, '../var/webpack-bundles.json');
const bundleFileExists = fs.existsSync(WEBPACK_BUNDLE_FILE);

const runOpts = {
  silent: true,
  stdio: 'ignore',
  cwd: ROOT_DIR
};

async function app_tests() {
  if (!bundleFileExists) {
    console.log('Creating webpack bundle file...');
    await run('node tools/webpack -f', runOpts);
  }

  console.log('Running migrations on test db...');
  await run('node tools/run-migrations -t', runOpts);

  global.reminders = require('../app/models/reminders');
  global.archives = require('../app/models/archives');

  const server = await startServer();
  const testPromises = [];
  testFiles.forEach(file => {
    file = path.join(TEST_DIR, file);
    if (!fs.existsSync(file)) {
      console.error(`Test file ${file} does not exsist.`);
      process.exit(1);
    }

    console.log('running test file: ', path.basename(file));
    const test = require(file);
    if (typeof test === 'function') {
      testPromises.push(test());
    }
  });

  await Promise.all(testPromises);
  server.close();
  process.exit(0);
}

app_tests()
  .catch(err => {
    console.log('An error occured: ');
    console.error(err);
    process.exit(1);
  });
