#!/usr/bin/env node

const chalk = require('chalk');
const run = require('./run');
const opts = {
  capture: true,
  silent: true
};

/*
This is ran to make sure the version is updated so other
users may not face some un-predictable error from db in development.
*/
(async function check_migration_version() {
  let changedFiles;
  changedFiles = await run('git diff --cached --name-only', opts);
  if (changedFiles === '') {
    // TODO: add ci test ranges here.
    changedFiles = await run('git diff HEAD~1 --name-only', opts);
  }

  let migrationFilesChanged = false;
  let versionChanged = false;
  changedFiles = changedFiles.split('\n');
  changedFiles.forEach(file => {
    file = file.trim();
    if (file.includes('app/models/migrations')) {
      migrationFilesChanged = true;
    }

    if (file === 'version.js') {
      versionChanged = true;
    }
  });

  if (migrationFilesChanged && !versionChanged) {
    console.error(chalk.red('It looks like migration files were changed, but'));
    console.error(chalk.red('MIGRATION_VERSION in tools/version.js was not bumped!'));
    process.exit(1);
  }
})();
