#!/usr/bin/env node
'use strict';

const path = require('path');
const run = require('./run');
const env = require('../app/env');

const ROOT_DIR = path.resolve(__dirname, '../');

env.setEnv('mode', 'development');
const needToMigrate = require('./migration-status');
(async function dev_server() {
  if (needToMigrate) {
    await run('node run-migrations --development');
  }

  const passedArgs = process.argv.splice(2);
  let cmd = 'npx nodemon --config tools/nodemon.json';
  cmd += ' tools/dev-server.js -- ' + passedArgs.join(' ');

  // we show help an not run nodemon in case
  // help | --help | -h is passed as first argument
  const firstArg = (passedArgs[0] || '').trim();
  const runOpts = { cwd: ROOT_DIR };
  if (firstArg === 'help' || firstArg === '--help' || firstArg === '-h') {
    cmd = 'node tools/dev-server.js -h';
    runOpts.silent = true;
  }

  run(cmd, runOpts);
})();
