#!/usr/bin/env node
'use strict';

const path = require('path');
const run = require('./run');
const env = require('../app/env');

const ROOT_DIR = path.resolve(__dirname, '../');

env.setEnv('mode', 'development');
const needToMigrate = require('./migration-status');
(async function dev_server() {
  if (needToMigrate) {
    await run('./run-migrations --development');
  }

  let cmd = 'npx nodemon --config tools/nodemon.json';
  cmd += ' tools/dev-server.js -- ' + process.argv.splice(2).join(' ');
  run(cmd, { cwd: ROOT_DIR });
})();
