#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');
const env = require('../app/env');
const { promisify } = require('util');

if (!env.mode) {
  env.setEnv('mode', 'devlopment');
}

const readdir = promisify(fs.readdir);
const migrationDir = path.resolve(__dirname, '../app/models/migrations');
(async function do_migrate_db() {
  const migrationFiles = await readdir(migrationDir);
  console.log('Running migrations...');
  const migrations = [];
  migrationFiles.forEach(migrationFile => {
    const migration = require(path.join(migrationDir, migrationFile));
    migrations.push({
      file: path.basename(migrationFile, '.js'),
      migration
    });
  });

  for (let i = 0; i < migrations.length; i++) {
    console.log('    Applying migration', migrations[i].file);
    await migrations[i].migration();
  }
})();
