#!/usr/bin/env node
'use strict';

const fs = require('fs');
const fsExtra = require('fs-extra');
const path = require('path');
const { promisify } = require('util');
const env = require('../app/env');
const version = require('../version');
const argparser = require('../app/argparser');

const args = argparser(`
Run migrations on database.
The database will not work unless migration are not applied.

Flags:
  --production, -p   Runs the migrations on production db. [default]
  --development, -d          Runs migrations on development db.
  --test, -t         Runs migrations on test db.
`);

args.add('--production', { type: 'boolean', alias: '-p' });
args.add('--development', { type: 'boolean', alias: '-d' });
args.add('--test', { type: 'boolean', alias: '-t' });

args.parse();
if (args.test || args.development) {
  env.setEnv('mode', args.test ? 'test' : 'development');
} else {
  env.setEnv('production', true);

  // create a backup for production db.
  const DB_PATH = path.resolve(__dirname, '../var/reminder-app');
  const DB_BACKUP = path.resolve(__dirname, '../var/backup/reminder-app');
  fsExtra.copySync(DB_PATH, DB_BACKUP);
}

const readdir = promisify(fs.readdir);
const writeFile = promisify(fs.writeFile);
const migrationDir = path.resolve(__dirname, '../app/models/migrations');

async function update_migration_version() {
  const versionFile = path.resolve(__dirname, '../var/version.js');
  let versions;
  try {
    versions = require(versionFile);
    versions.MIGRATION_VERSION = version.MIGRATION_VERSION;
  } catch(e) {
    versions = {
      MIGRATION_VERSION: version.MIGRATION_VERSION
    };
  }

  fs.open(versionFile, 'w+', async () => {
    await writeFile(versionFile, `module.exports = ${
      JSON.stringify(versions, null, 2)
    };`);
  });
}

async function run_migrations() {
  const migrationFiles = await readdir(migrationDir);
  console.log('Running migrations...');
  const migrations = [];
  migrationFiles.forEach(migrationFile => {
    const migration = require(path.join(migrationDir, migrationFile));
    migrations.push({
      file: path.basename(migrationFile, '.js'),
      migration
    });
  });

  for (let i = 0; i < migrations.length; i++) {
    console.log('    Applying migration', migrations[i].file);
    await migrations[i].migration();
  }

  await update_migration_version();
}

run_migrations();
