#!/usr/bin/env node
'use strict';

const fs = require('fs');
const fsExtra = require('fs-extra');
const path = require('path');
const { promisify } = require('util');
const ora = require('ora');
const env = require('../app/env');
const version = require('./version');
const ArgParser = require('../app/argparser');

const args = new ArgParser(`
Run migrations on database.
The database will not work unless migration are not applied      
`);

args.add('--production', { type: 'boolean', alias: '-p',
  help: 'Runs the migrations on production db. [default]' });
args.add('--development', { type: 'boolean', alias: '-d',
  help: 'Runs migrations on development db.' });
args.add('--tests', { type: 'boolean', alias: '-t',
  help: 'Runs migrations on test db.' });
args.parse();

const spinner = new ora({
  text: 'Running migrations',
  spinner: 'dots2'
});

spinner.start();
if (args.tests) {
  env.setEnv('tests', true);
}

if (args.development) {
  env.setEnv('development', true);
}

if ((args.tests || args.development) && env.mode === undefined) {
  env.setEnv('mode', args.tests ? 'tests' : 'development');
} else {
  env.setEnv('production', true);

  spinner.text = 'Backing up current db in var/backup';
  spinner.color = 'green';
  // create a backup for production db.
  const DB_PATH = path.resolve(__dirname, '../var/reminder-app');
  if (fs.existsSync(DB_PATH)) {
    const DB_BACKUP = path.resolve(__dirname, '../var/backup/reminder-app');
    fsExtra.copySync(DB_PATH, DB_BACKUP);
  }
}

// make sure var/ exists otherwise leveldb will throw errors!
fsExtra.mkdirpSync(path.resolve(__dirname, '../var'));

const readdir = promisify(fs.readdir);
const writeFile = promisify(fs.writeFile);
const migrationDir = path.resolve(__dirname, '../app/models/migrations');

async function update_migration_version() {
  spinner.text = 'Updating migration version';
  spinner.color = 'yellow';
  const versionFile = path.resolve(__dirname, '../var/version.js');
  let versions;
  try {
    versions = require(versionFile);
    versions.MIGRATION_VERSION = version.MIGRATION_VERSION;
  } catch(e) {
    versions = {
      MIGRATION_VERSION: version.MIGRATION_VERSION
    };
  }

  fs.open(versionFile, 'w+', async () => {
    // we output the version file in readable unminifed way.
    await writeFile(versionFile, `module.exports = ${
      JSON.stringify(versions, null, 2)
    };\n`);
  });
}

async function run_migrations() {
  const migrationFiles = await readdir(migrationDir);
  spinner.text = 'Running migrations...';
  spinner.color = 'blue';
  const migrations = [];
  migrationFiles.forEach(migrationFile => {
    const migration = require(path.join(migrationDir, migrationFile));
    migrations.push({
      file: path.basename(migrationFile, '.js'),
      migration
    });
  });

  spinner.info('Running Migrations:');
  for (let i = 0; i < migrations.length; i++) {
    spinner.info('   Applying migration ' + migrations[i].file);
    await migrations[i].migration();
  }

  if (args.development) {
    await update_migration_version();
  }
  spinner.succeed('Migration ran successfully!');
}

run_migrations();
