#!/usr/bin/env node
'use strict';

const path = require('path');
const fs = require('fs');
const run = require('./run');

const ROOT_DIR = path.resolve(__dirname, '../');
const runOpts = {
  cwd: ROOT_DIR
};

console.log('Running all the tests...');
const webpackBundleFile = path.resolve(__dirname, '../var/webpack-dev-bundles.json');
async function testAll() {
  if (!fs.existsSync(webpackBundleFile)) {
    console.log('Creating webpack bundles file...');
    await run('npx webpack --config tools/webpack.config.js', {
      ...runOpts,
      silent: true
    });
  }

  await Promise.all([
    run('npx eslint . --cache --cache-location=var/.eslintcache', runOpts),
    run('node tools/test-npm-dependencies', runOpts),
    run('node tools/run-tests', runOpts),
    run('node tools/test-migrations', runOpts),
    run('node tools/check-migration-version', runOpts)
  ]);
}

testAll()
.then(() => {
  console.log('All test ran successfully!');
})
.catch(() => {
  console.log('Some test failed, check traceback above for more details.');
  process.exit(1);
});
