#!/usr/bin/env node
'use strict';

const packageJSON = require('../package.json');
const dependecies = {
  ...packageJSON.dependencies,
  ...packageJSON.devDependencies
};

for (let dependency in dependecies) {
  let version = dependecies[dependency];
  if (version.includes('^')) {
    throw new Error(`package.json has a unpinned dependency for ${dependency}, `
                  + 'please make sure the dependency is pinned to specific version.');
  }
}
