#!/usr/bin/env node
'use strict';

/*
  This checks that any package's that are added are pinned
  to certain version so the app does not break due to a update
  unknown upstream update.
*/
const packageJSON = require('../package.json');
const dependecies = {
  ...packageJSON.dependencies,
  ...packageJSON.devDependencies
};

for (let dependency in dependecies) {
  let version = dependecies[dependency];
  if (version.includes('^')) {
    throw new Error(`package.json has a unpinned dependency for ${dependency}, `
                  + 'please make sure the dependency is pinned to specific version.');
  }
}
