#!/usr/bin/env node
'use strict';

const path = require('path');
const _run = require('./run');

/*
  Simple wrapper to run:
    ./run-tests as
    /full/path/to/run-tests
*/
function run(cmd) {
  if (cmd.startsWith('./')) {
    cmd = path.join(__dirname, cmd);
    return _run(cmd);
  }

  return _run(cmd);
}

console.log('Running all the tests...');
async function testAll() {
  await Promise.all([
    run('./test-npm-dependencies'),
    run('./run-tests'),
    run('./test-migrations')
  ]);
}

testAll()
.then(() => {
  console.log('All test ran successfully!');
})
.catch(() => {
  console.log('Some test failed, check traceback above for more details.');
});
